CREATE TABLE IF NOT EXISTS india_aqi (
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  dt TIMESTAMP,
  pm25 DOUBLE PRECISION,
  pm10 DOUBLE PRECISION,
  no2 DOUBLE PRECISION,
  so2 DOUBLE PRECISION,
  o3 DOUBLE PRECISION,
  co DOUBLE PRECISION,
  aqi INTEGER,
  PRIMARY KEY (lat, lon, dt)
);
